# Databricks notebook source
pip install msal

# COMMAND ----------

pip install adal

# COMMAND ----------

dbutils.library.restartPython()

# COMMAND ----------

from datta_pipeline_library.core.spark_init import spark
from datta_pipeline_library.core.base_config import (
    BaseConfig,
    CommonConfig,
    EnvConfig
)
from datta_pipeline_library.helpers.adls import configure_spark_to_use_spn_to_write_to_adls_gen2
from datta_pipeline_library.helpers.spn import AzureSPN
from datta_pipeline_library.helpers.uc import (
    get_catalog_name
)

# COMMAND ----------

env = dbutils.widgets.get(name="env")
repos_path = dbutils.widgets.get(name="repos_path")
unique_repo_branch_id = dbutils.widgets.get(name="unique_repo_branch_id")
unique_repo_branch_id_schema = dbutils.widgets.get(name="unique_repo_branch_id_schema")

# env = "dev"
# repos_path = "/Repos/DATTA-MCPA_DCPA/DATTA-COPA-EH"
# unique_repo_branch_id = ""
# unique_repo_branch_id_schema = "gsap"

common_conf = CommonConfig.from_file(f"/Workspace/{repos_path.strip('/')}/conf/common/common_conf.json")
env_conf = EnvConfig.from_file(f"/Workspace/{repos_path.strip('/')}/conf/{env}/conf.json")

base_config = BaseConfig.from_confs(env_conf, common_conf)
if unique_repo_branch_id:
    base_config.set_unique_id(unique_repo_branch_id)
if unique_repo_branch_id_schema:
    base_config.set_unique_id_schema(unique_repo_branch_id_schema)

# COMMAND ----------

kv = env_conf.kv_key

# values from key vault
tenant_id = dbutils.secrets.get(scope=kv, key="AZ-AS-SPN-DATTA-TENANT-ID")
spn_client_id = dbutils.secrets.get(scope=kv, key=env_conf.spn_client_id_key)
spn_client_secret = dbutils.secrets.get(scope=kv, key=env_conf.spn_client_secret_key)

spn = AzureSPN(tenant_id, spn_client_id, spn_client_secret)

configure_spark_to_use_spn_to_write_to_adls_gen2(env_conf.storage_account, spn)

# COMMAND ----------

uc_catalog_name = base_config.get_uc_catalog_name()
print("uc_catalog_name : ",uc_catalog_name)

uc_eh_schema = base_config.get_uc_eh_schema()
print("uc_eh_schema : ", uc_eh_schema)

uc_eh_schema = uc_eh_schema.replace("-gsap", "")
print("uc_eh_schema : ", uc_eh_schema)

tbl_owner_grp = base_config.get_tbl_owner_grp()
print("tbl_owner_grp : ",tbl_owner_grp)

tbl_read_grp = base_config.get_tbl_read_grp()
print("tbl_read_grp : ",tbl_owner_grp)

security_object_aad_group_name = env_conf.security_object_aad_group
print("security object aad group name: ", security_object_aad_group_name)

security_end_user_aad_group_name = env_conf.security_end_user_aad_group
print("security end user aad group name: ", security_end_user_aad_group_name)

security_functional_readers_aad_group = env_conf.security_functional_readers_aad_group
print("security functional readers aad group name: ", security_functional_readers_aad_group)

security_security_readers_aad_group = env_conf.security_security_readers_aad_group
print("security security readers aad group name: ", security_security_readers_aad_group)

security_minerva_readers_aad_group = env_conf.security_minerva_readers_aad_group
print("security minerva readers aad group name: ", security_minerva_readers_aad_group)

# COMMAND ----------

# assignViewPermission: This function assigns Permission to the view created
def assignViewPermission(catalog,schema,view_name,tbl_owner, security_end_user_aad_group, security_object_aad_group, security_functional_readers_aad_group):
    spark.sql(f"""GRANT ALL PRIVILEGES ON VIEW `{catalog}`.`{schema}`.{view_name} TO `{tbl_owner}`""")
    print("All privileges access given to tbl owner", tbl_owner)
    spark.sql(f"""GRANT SELECT ON VIEW `{catalog}`.`{schema}`.{view_name} TO `{security_end_user_aad_group}`""")
    print("Reader access granted to ", security_end_user_aad_group)
    spark.sql(f"""GRANT SELECT ON VIEW `{catalog}`.`{schema}`.{view_name} TO `{security_functional_readers_aad_group}`""")
    print("Reader access granted to ", security_functional_readers_aad_group)
    spark.sql(f"""ALTER VIEW `{catalog}`.`{schema}`.{view_name} owner to `{tbl_owner}`""")
    print("Table Owner is assigned to ", tbl_owner)

# COMMAND ----------

# DBTITLE 1,FI_GL_ACCOUNTING_STN View
minerva_acct_stn_view_name = "VW_FACT_FI_GL_ACCOUNTING_STN"
# security_function_name = "sf_gen_rls_security"
security_schema = "eh-ds-security"
use_catalog = "USE CATALOG `"+uc_catalog_name+"`"
spark.sql(use_catalog)
spark.sql(f"""DROP VIEW IF EXISTS `{uc_catalog_name}`.`{uc_eh_schema}`.{minerva_acct_stn_view_name}""")
spark.sql(f"""CREATE OR REPLACE VIEW `{uc_catalog_name}`.`{uc_eh_schema}`.{minerva_acct_stn_view_name} 
        AS SELECT t.Company_Code,
t.Accounting_Document_Number,
t.Fiscal_Year,
t.Document_Type,
t.Document_Date_In_Document,
t.Posting_Date_In_The_Document,
t.Fiscal_Period,
t.Day_On_Which_Accounting_Document_Was_Entered,
t.Time_Of_Entry,
t.Date_Of_The_Last_Document_Change_By_Transaction,
t.Date_Of_The_Last_Document_Update,
t.Translation_Date,
t.User_Name,
t.Transaction_Code,
t.Number_Of_Cross_Company_Code_Posting_Transaction,
t.Reference_Document_Number,
t.Recurring_Entry_Document_Number,
t.Reverse_Document_Number,
t.Reverse_Document_Fiscal_Year,
t.Document_Header_Text,
t.Currency_Key,
t.Exchange_Rate,
t.Currency_Key_For_The_Group_Currency,
t.Group_Currency_Exchange_Rate,
t.Document_Status,
t.Indicator_Document_Posted_Net,
t.Unplanned_Delivery_Costs,
t.Indicator_Document_Is_Posted_To_A_Previous_Period,
t.Business_Transaction,
t.Batch_Input_Session_Name,
t.Document_Name_In_The_Archive_System,
t.Extract_Id_Document_Header,
t.Internal_Document_Type_For_Document_Control,
t.Reference_Procedure,
t.Object_Key,
t.Financial_Management_Area,
t.Local_Currency,
t.Currency_Key_Of_Second_Local_Currency,
t.Currency_Key_Of_Third_Local_Currency,
t.Exchange_Rate_For_The_Second_Local_Currency,
t.Exchange_Rate_For_The_Third_Local_Currency,
t.Source_Currency_For_Currency_Translation_2,
t.Source_Currency_For_Currency_Translation_3,
t.Translation_Date_Type_For_Second_Local_Currency,
t.Translation_Date_Type_For_Third_Local_Currency,
t.Indicator_Document_Is_Flagged_For_Reversal,
t.Planned_Date_For_The_Reverse_Posting,
t.Calculate_Tax_Automatically,
t.Currency_Type_Of_Second_Local_Currency,
t.Currency_Type_Of_Third_Local_Currency,
t.Exchange_Rate_Type_2,
t.Exchange_Rate_Type_3,
t.GL_Account_Amounts_Entered_Exclude_Tax,
t.Source_Company_Code,
t.Enter_Vat_Use_Tax_Sales_Tax_On_Detail_Screen,
t.Status_Of_Data_Transfer_Into_Subsequent_Release,
t.Logical_System,
t.Exchange_Rate_For_Taxes,
t.Rate_For_Tax_Values_In_Local_Currency,
t.Lot_Number_For_Requests,
t.Indicator_Customer_Bill_Of_Exchange_Payment_Before_Due_Date,
t.Reason_For_Reversal_Or_Inverse_Posting,
t.Name_Of_User_Who_Parked_This_Document,
t.Day_Of_Parking_Of_Accounting_Document,
t.Time_Of_Parking,
t.Parking_Transaction,
t.Branch_Number,
t.Number_Of_Pages_Of_Invoice,
t.Indicator_Entry_Represents_A_Discount_Document,
t.Reference_Key_1_Internal_For_Document_Header,
t.Reference_Key_2_Internal_For_Document_Header,
t.Specifies_Whether_Doc_Is_Reversal_Doc_Or_Reversed_Doc,
t.Invoice_Receipt_Date,
t.Ledger_In_General_Ledger_Accounting,
t.Ledger_Group,
t.Real_Estate_Management_Mandate,
t.Alternative_Reference_Number,
t.Tax_Reporting_Date,
t.Classification_Of_An_Fi_Document,
t.Fi_Document_Originates_From_Split_Posting_Indicator,
t.Cash_Relevant_Document,
t.Follow_On_Document_Indicator,
t.Doc_Contains_Open_Item_That_Was_Transferred_During_Reorg,
t.Defines_Subset_Of_Components_For_The_FiCo_Interface,
t.Exchange_Rate_Type,
t.Market_Data_Exchange_Rate,
t.Market_Data_Exchange_Rate_2,
t.Market_Data_Exchange_Rate_3,
t.Document_Originates_From_Multi_Currency_Accounting,
t.Date_Of_Resubmission,
t.Document_Status_1,
t.Document_Category_Payment_Requests,
t.Reason,
t.Region,
t.Reason_For_Reversal_Is_Ps_Requests,
t.Is_Ps_File_Number,
t.Interest_Formula,
t.Interest_Calc_Date,
t.Posting_Day,
t.Actual_Posting,
t.Date_Of_Last_Change,
t.Last_Changed_At,
t.Type_Of_Payment_Transfer,
t.Payment_Cards_Card_Type,
t.Payment_Cards_Card_Number,
t.Payment_Statistical_Sampling_Block,
t.Lot_Number_For_Documents,
t.User_Name_1,
t.Sampled_Invoice_By_Payment_Certification,
t.Ppa_Exclude_Indicator_BKPF,
t.Budgetary_Ledger_Indicator,
t.Treasury_Offset_Status,
t.Date_Record_Referred_To_Treasury,
t.Reason_For_Late_Payment_BKPF,
t.Number_Of_The_Document_Condition,
t.Type_Of_Payment_Basis_Document_BKPF,
t.Payment_Basis_Document_Number_BKPF,
t.Payment_Basis_Document_Date_BKPF,
t.Iban_International_Bank_Account_Number,
t.Incoming_Document_Number_BKPF,
t.Incoming_Document_Date_BKPF,
t.LAST_DTM,
t.Number_Of_Line_Item_Within_Accounting_Document,
t.Identification_Of_The_Line_Item,
t.Clearing_Date,
t.Clearing_Entry_Date,
t.Document_Number_Of_The_Clearing_Document,
t.Posting_Key,
t.Account_Type,
t.Special_GL_Indicator,
t.Special_GL_Transaction_Type,
t.Target_Special_GL_Indicator,
t.Debit_Credit_Indicator,
t.Business_Area,
t.Trading_PartnerS_Business_Area,
t.Tax_On_Sales_Purchases_Code,
t.Withholding_Tax_Code,
t.Amount_In_Local_Currency,
t.Amount_In_Document_Currency,
t.Original_Reduction_Amount_In_Local_Currency,
t.Amount_For_Updating_In_General_Ledger,
t.Update_Currency_For_General_Ledger_Transaction_Figures,
t.Original_Tax_Base_Amount_In_Local_Currency,
t.Original_Tax_Base_Amount_In_Document_Currency,
t.Tax_Amount_In_Local_Currency,
t.Tax_Amount_In_Document_Currency,
t.Tax_Base_Amount_In_Local_Currency,
t.Tax_Base_Amount_In_Document_Currency,
t.Provision_Amount_In_Local_Currency,
t.Additional_Tax_In_Document_Currency,
t.DebitCredit_Addition_For_Cash_Discount,
t.Version_Number_Component,
t.Tax_Type,
t.Group_Indicator_For_Tax_Line_Items,
t.Transaction_Key,
t.Withholding_Tax_Base_Amount,
t.Hedged_Exchange_Rate,
t.Hedged_Amount_In_Foreign_Currency,
t.Valuation_Difference,
t.Valuation_Difference_For_The_Second_Local_Currency,
t.Value_Date,
t.Assignment_Number,
t.Item_Text,
t.Exempted_From_Interest_Calculation,
t.Company_Id_Of_Trading_Partner,
t.Transaction_Type,
t.Group_Account_Number,
t.Transaction_Type_For_General_Ledger,
t.Planning_Level,
t.Planning_Group,
t.Planned_Amount_In_Document_Or_GL_Account_Currency,
t.Planning_Date,
t.Financial_Budget_Item,
t.Controlling_Area,
t.Cost_Center,
t.Old_Project_Number_No_Longer_Used_PsPosnr,
t.Order_Number,
t.Billing_Document,
t.Sales_Document,
t.Sales_Document_Item,
t.Schedule_Line_Number,
t.Main_Asset_Number,
t.Asset_Subnumber,
t.Asset_Transaction_Type,
t.Asset_Value_Date,
t.Personnel_Number,
t.Indicator_Sales_Related_Item,
t.Indicator_Resident_GL_Account,
t.Indicator_Can_Line_Items_Be_Displayed_By_Account,
t.Indicator_Open_Item_Management,
t.Indicator_Address_And_Bank_Data_Set_Individually,
t.Indicator_Statistical_Posting_To_Cost_Center,
t.Indicator_Posting_To_Order_Is_Statistical,
t.Indicator_Posting_To_Project_Is_Statistical,
t.Indicator_Posting_To_Profitability_Analysis_Is_Statistical,
t.Indicator_Billing_Document_Update_Successful,
t.Indicator_Transfer_Posting_From_Down_Payment,
t.Indicator_Down_Payment_In_Net_Procedure,
t.Indicator_Line_Item_Not_Liable_To_Cash_Discount,
t.Indicator_Capital_Goods_Affected,
t.Display_Item,
t.Indicator_Line_Item_Automatically_Created,
t.Indicator_Items_Cannot_Be_Copied,
t.Indicator_Is_Posting_Key_Used_In_A_Payment_Transaction,
t.GL_Account_Number,
t.General_Ledger_Account,
t.Customer_Number,
t.Account_Number_Of_Supplier,
t.Account_Number_Of_The_Branch,
t.Indicator_Account_Is_A_Balance_Sheet_Account,
t.PL_Statement_Account_Type,
t.Assignment_Number_For_Special_GL_Accounts,
t.Baseline_Date_For_Due_Date_Calculation,
t.Terms_Of_Payment_Key,
t.Cash_Discount_Days_1,
t.Cash_Discount_Days_2,
t.Net_Payment_Terms_Period,
t.Cash_Discount_Percentage_1,
t.Cash_Discount_Percentage_2,
t.Amount_Eligible_For_Cash_Discount_In_Document_Currency,
t.Cash_Discount_Amount_In_Local_Currency,
t.Cash_Discount_Amount_In_Document_Currency,
t.Payment_Method,
t.Payment_Block_Key,
t.Fixed_Payment_Terms,
t.Short_Key_For_A_House_Bank,
t.Partner_Bank_Type,
t.Net_Payment_Amount,
t.Tax_Code_For_Distribution_1,
t.Amount_In_Local_Currency_For_Tax_Distribution_1,
t.Amount_In_Foreign_Currency_For_Tax_Breakdown_1,
t.Tax_Code_For_Distribution_2,
t.Amount_In_Local_Currency_For_Tax_Distribution_2,
t.Amount_In_Foreign_Currency_For_Tax_Breakdown_2,
t.Tax_Code_For_Distribution_3,
t.Amount_In_Local_Currency_For_Tax_Distribution_3,
t.Amount_In_Foreign_Currency_For_Tax_Breakdown_3,
t.Document_No_Of_The_Invoice_To_Which_The_Transaction_Belongs,
t.Fiscal_Year_Of_The_Relevant_Invoice_For_Credit_Memo,
t.Line_Item_In_The_Relevant_Invoice,
t.Follow_On_Document_Type,
t.Customs_Tariff_Number,
t.Customs_Date,
t.State_Central_Bank_Indicator,
t.Supplying_Country,
t.Service_Indicator_Foreign_Payment,
t.Invoice_List_Number,
t.Settlement_Period,
t.Insurance_Indicator,
t.Insurance_Date,
t.Number_Of_Bill_Of_Exchange_Usage_Document_Discount_Doc,
t.Fiscal_Year_Of_Bill_Of_Exchange_Usage_Document,
t.Line_Item_Within_The_Bill_Of_Exchange_Usage_Document,
t.Bill_Of_Exchange_Usage_Type,
t.Document_Number_Of_The_Bill_Of_Exchange_Payment_Request,
t.Fiscal_Year_Of_The_Bill_Of_Exchange_Payment_Request_Document,
t.Company_Code_In_Which_Bill_Of_ExchPayment_Request_Is_Posted,
t.Bill_Of_Exchange_Payment_Request_Due_Date,
t.Base_Amount_For_Determining_The_Preference_Amount,
t.Subsidy_Indicator_For_Determining_The_Reduction_Rates,
t.Preference_Percentage_Rate,
t.Dunning_Key,
t.Dunning_Block,
t.Date_Of_Last_Dunning_Notice,
t.Dunning_Level,
t.Dunning_Area,
t.Isr_Subscriber_Number,
t.IsrQr_Reference_Number,
t.Por_Check_Digit,
t.Credit_Control_Amount,
t.Certificate_Number_Of_The_Withholding_Tax_Exemption,
t.Withholding_Tax_Amount_In_Document_Currency,
t.Withholding_Tax_Exempt_Amount_In_Document_Currency,
t.Non_Deductible_Input_Tax_In_Local_Currency,
t.Non_Deductible_Input_Tax_In_Document_Currency,
t.Material_Number,
t.Plant,
t.Quantity,
t.Base_Unit_Of_Measure,
t.Quantity_In_Unit_Of_Entry,
t.Unit_Of_Entry,
t.Quantity_In_Purchase_Order_Price_Unit,
t.Order_Price_Unit_Purchasing,
t.Purchasing_Document_Number,
t.Item_Number_Of_Purchasing_Document,
t.Sequential_Number_Of_Account_Assignment,
t.Delivery_Completed_Indicator,
t.Price_Control_Indicator,
t.Price_Unit,
t.Valuation_Area,
t.Valuation_Type,
t.Posting_String_For_Values,
t.Invoice_Value_Entered_In_Local_Currency,
t.Invoice_Value_In_Foreign_Currency,
t.Amount_Qualifying_For_Bonus_In_Local_Currency,
t.Amount_Posted_In_Alternative_Price_Control,
t.Alternative_Price_Control,
t.New_Price,
t.Indicator_Subsequent_DebitCredit,
t.Blocking_Reason_Price,
t.Blocking_Reason_Quantity,
t.Blocking_Reason_Date,
t.Blocking_Reason_Order_Price_Quantity,
t.Blocking_Reason_Project_Budget,
t.Manual_Blocking_Reason,
t.Vat_Registration_Number,
t.Country_Of_Destination_For_Delivery_Of_Goods,
t.Supplying_Country_For_Delivery_Of_Goods,
t.Reason_Code_For_Payments,
t.Year_Of_Acquisition,
t.Period_Of_Acquisition,
t.Exchange_Rate_GainLoss_Realized,
t.Exchange_Rate_Difference_Realized_For_Second_Local_Currency,
t.Profit_Center,
t.Indicator_GL_Account_Assigned_Manually,
t.Joint_Venture,
t.Recovery_Indicator,
t.Equity_Group,
t.Partner_Account_Number,
t.Contract_Type,
t.Contract_Number,
t.Flow_Type,
t.Securities_Account,
t.Tax_Jurisdiction,
t.Internal_Key_For_Real_Estate_Object,
t.Reference_Date_For_Settlement,
t.Real_Estate_Option_Rate,
t.Commitment_Item,
t.Cost_Object,
t.Network_Number_For_Account_Assignment,
t.Task_List_Number_For_Operations_In_Order,
t.General_Counter_For_Order,
t.Work_Breakdown_Structure_Element_Wbs_Element,
t.Profitability_Segment_Number_Co_Pa,
t.Profitability_Segment_Changes_Co_Pa,
t.Blocking_Reason_Item_Amount,
t.Blocking_Reason_Quality,
t.Payroll_Type,
t.Equity_Type,
t.Indicator_Triangular_Deal_Within_The_Eu,
t.Sequence_Number_Of_Asset_Line_Items_In_Fiscal_Year,
t.Origin_Group_As_Subdivision_Of_Cost_Element,
t.Amount_In_Second_Local_Currency,
t.Amount_In_Third_Local_Currency,
t.Amount_In_Second_Local_Currency_For_Tax_Breakdown_21,
t.Amount_In_Second_Local_Currency_For_Tax_Breakdown_22,
t.Amount_In_Second_Local_Currency_For_Tax_Breakdown_23,
t.Amount_In_Third_Local_Currency_For_Tax_Breakdown_31,
t.Amount_In_Third_Local_Currency_For_Tax_Breakdown_32,
t.Amount_In_Third_Local_Currency_For_Tax_Breakdown_33,
t.Tax_Amount_In_Second_Local_Currency,
t.Tax_Amount_In_Third_Local_Currency,
t.Non_Deductible_Input_Tax_In_Second_Local_Currency,
t.Non_Deductible_Input_Tax_In_Third_Local_Currency,
t.Cash_Discount_Amount_In_Second_Local_Currency,
t.Cash_Discount_Amount_In_Third_Local_Currency,
t.Valuation_Difference_For_The_Third_Local_Currency,
t.Exchange_Rate_Difference_Realized_For_Third_Local_Currency,
t.Method_With_Which_The_Local_Currency_Amount_Was_Determined,
t.Update_Method_For_Fm_Fi_Ca_Integration,
t.Indicator_Clearing_Was_Reversed,
t.Payment_Method_Supplement,
t.Alternative_Account_Number_In_Company_Code,
t.Funds_Center,
t.Fund,
t.Tax_Company_Code,
t.Tax_BaseOriginal_Tax_Base_In_Second_Local_Currency,
t.Tax_BaseOriginal_Tax_Base_In_Third_Local_Currency,
t.Partner_Profit_Center,
t.Business_Partner_Reference_Key_1,
t.Business_Partner_Reference_Key_2,
t.Document_Number_For_Earmarked_Funds,
t.Earmarked_Funds_Document_Item,
t.Tax_Amount_As_Statistical_Information_In_Document_Currency,
t.Functional_Area,
t.Number_Of_Line_Item_In_Original_Document,
t.Indicator_Negative_Posting,
t.Payment_Card_Item,
t.Payment_Cards_Settlement_Run,
t.Credit_Control_Area,
t.PayeePayer,
t.Reference_Key_For_Line_Item,
t.Instruction_1,
t.Instruction_2,
t.Instruction_3,
t.Instruction_4,
t.Activity_Code_For_Gross_Income_Tax,
t.Region_State_Province_County,
t.Distribution_Type_For_Employment_Tax,
t.Indicator_Items_From_Payment_Program_Blocked,
t.Payment_Reference,
t.Credit_Management_Hedged_Amount,
t.Inflation_Index,
t.Last_Adjustment_Date,
t.Account_Assignment_Category_For_Industry_Solution,
t.Acct_Assignment_String_For_Industry_Specific_Acct_Assignmnts,
t.Date_For_Defining_Tax_Rates,
t.Clearing_Item,
t.Currency_For_Automatic_Payment,
t.Amount_In_Payment_Currency,
t.Business_Place,
t.Section_Code,
t.Activity_Type,
t.Accounts_Receivable_Pledging_Indicator,
t.Business_Process,
t.Realized_Exchange_Rate_GainLoss_1LocCurrPart_Payments,
t.Realized_Exchange_Rate_GainLoss_2Loc_CurrPart_Payments,
t.Realized_Exchange_Rate_GainLoss_3LocCurrPart_Payments,
t.Penalty_Charge_Amount_In_First_Local_Currency,
t.Penalty_Charge_Amount_In_Second_Local_Currency,
t.Penalty_Charge_Amount_In_Third_Local_Currency,
t.Penalty_Charge_Amount_In_Document_Currency,
t.Number_Of_Days_For_Penalty_Charge_Calculation,
t.Reason_For_Late_Payment_BSEG,
t.Grant,
t.Tax_Portion_Fi_Ca_Local_Currency,
t.Functional_Area_Long,
t.Item_Is_In_Execution,
t.Type_Of_Additional_Receivable,
t.Internal_Real_Estate_Master_Data_Code,
t.Funded_Program,
t.Fiscal_Year_Of_Clearing_Document,
t.Ppa_Exclude_Indicator_BSEG,
t.Six_Character_Posting_Item_For_Ledger,
t.Segment_For_Segmental_Reporting,
t.Partner_Segment_For_Segmental_Reporting,
t.Partner_Functional_Area,
t.Id_For_Account_Details,
t.Cost_Element,
t.Clearing_Specific_To_Ledger_Groups,
t.Tax_Document_Item_Number,
t.Payment_Service_Provider,
t.Payment_Reference_Of_Payment_Service_Provider,
t.Unique_Reference_To_Mandate_For_Each_Payee,
t.Payment_Is_Released,
t.Quantity_Sign,
t.Type_Of_The_Accrual_Object,
t.Identifier_Of_The_Accrual_Object,
t.Identifier_Of_The_Accrual_Sub_Object,
t.Type_Of_The_Item_Of_The_Accrual_Sub_Object,
t.Type_Of_The_Financial_Valuation_Object,
t.Identifier_Of_The_Financial_Valuation_Object,
t.Identifier_Of_The_Financial_Valuation_Subobject,
t.Cash_Ledger_Company_Code_For_ExpenseRevenue,
t.Cash_Ledger_Expense_Or_Revenue_Account,
t.Partner_Fund,
t.Partner_Grant,
t.Fm_Budget_Period,
t.Fm_Partner_Budget_Period,
t.Branch_Code,
t.Billing_Period_Of_Performance_Start_Date,
t.Billing_Period_Of_Performance_End_Date,
t.Ppa_Fast_Pay_Indicator,
t.Fmfg_Ignore_The_Invoice_Reference_During_Fi_Doc_Splitting,
t.United_States_Federal_Government_Fields,
t.Fm_Reference_Document_Number,
t.Fm_Reference_Year,
t.Fm_Reference_Line_Item,
t.Fm_Reference_Sequence_Account_Assignment,
t.Production_Month_Date_To_Find_Period_And_Year,
t.Gst_Partner,
t.Place_Of_Supply,
t.Hsn_Or_Sac_Code,
t.Invoice_Reference_Number,
t.Service_Tax_Recredit_Flag,
t.Incoming_Document_Number_BSEG,
t.Incoming_Document_Date_BSEG,
t.Payment_Basis_Document_Number_BSEG,
t.Payment_Basis_Document_Date_BSEG,
t.Type_Of_Payment_Basis_Document_BSEG,
t.Payment_Or_Proposal_Key,
t.Ingested_At,
t.Source_ID
 FROM `{uc_catalog_name}`.`{uc_eh_schema}`.FACT_FI_GL_ACCOUNTING_STN t """)

assignViewPermission(uc_catalog_name,uc_eh_schema,minerva_acct_stn_view_name,tbl_owner_grp, security_minerva_readers_aad_group, security_object_aad_group_name, security_functional_readers_aad_group)          
print("Minerva VW_FACT_FI_GL_ACCOUNTING_STN view dropped and recreated in the schema")

# COMMAND ----------

# DBTITLE 1,FI_GL_ACCOUNTING_TSAP View
minerva_acct_tsap_view_name = "VW_FACT_FI_GL_ACCOUNTING_TSAP"
security_function_name = "sf_gen_rls_security"
security_schema = "eh-ds-security"
use_catalog = "USE CATALOG `"+uc_catalog_name+"`"
spark.sql(use_catalog)
spark.sql(f"""DROP VIEW IF EXISTS `{uc_catalog_name}`.`{uc_eh_schema}`.{minerva_acct_tsap_view_name}""")
spark.sql(f"""CREATE OR REPLACE VIEW `{uc_catalog_name}`.`{uc_eh_schema}`.{minerva_acct_tsap_view_name} 
        AS SELECT t.Company_Code,
t.Accounting_Document_Number,
t.Fiscal_Year,
t.Document_Type,
t.Document_Date_In_Document,
t.Posting_Date_In_The_Document,
t.Fiscal_Period,
t.Day_On_Which_Accounting_Document_Was_Entered,
t.Time_Of_Entry,
t.Date_Of_The_Last_Document_Change_By_Transaction,
t.Date_Of_The_Last_Document_Update,
t.Translation_Date,
t.User_Name,
t.Transaction_Code,
t.Number_Of_Cross_Company_Code_Posting_Transaction,
t.Reference_Document_Number,
t.Recurring_Entry_Document_Number,
t.Reverse_Document_Number,
t.Reverse_Document_Fiscal_Year,
t.Document_Header_Text,
t.Currency_Key,
t.Exchange_Rate,
t.Currency_Key_For_The_Group_Currency,
t.Group_Currency_Exchange_Rate,
t.Document_Status,
t.Indicator_Document_Posted_Net,
t.Unplanned_Delivery_Costs,
t.Indicator_Document_Is_Posted_To_A_Previous_Period,
t.Business_Transaction,
t.Batch_Input_Session_Name,
t.Document_Name_In_The_Archive_System,
t.Extract_Id_Document_Header,
t.Internal_Document_Type_For_Document_Control,
t.Reference_Procedure,
t.Object_Key,
t.Financial_Management_Area,
t.Local_Currency,
t.Currency_Key_Of_Second_Local_Currency,
t.Currency_Key_Of_Third_Local_Currency,
t.Exchange_Rate_For_The_Second_Local_Currency,
t.Exchange_Rate_For_The_Third_Local_Currency,
t.Source_Currency_For_Currency_Translation_2,
t.Source_Currency_For_Currency_Translation_3,
t.Translation_Date_Type_For_Second_Local_Currency,
t.Translation_Date_Type_For_Third_Local_Currency,
t.Indicator_Document_Is_Flagged_For_Reversal,
t.Planned_Date_For_The_Reverse_Posting,
t.Calculate_Tax_Automatically,
t.Currency_Type_Of_Second_Local_Currency,
t.Currency_Type_Of_Third_Local_Currency,
t.Exchange_Rate_Type_2,
t.Exchange_Rate_Type_3,
t.GL_Account_Amounts_Entered_Exclude_Tax,
t.Source_Company_Code,
t.Enter_Vat_Use_Tax_Sales_Tax_On_Detail_Screen,
t.Status_Of_Data_Transfer_Into_Subsequent_Release,
t.Logical_System,
t.Exchange_Rate_For_Taxes,
t.Rate_For_Tax_Values_In_Local_Currency,
t.Lot_Number_For_Requests,
t.Indicator_Customer_Bill_Of_Exchange_Payment_Before_Due_Date,
t.Reason_For_Reversal_Or_Inverse_Posting,
t.Name_Of_User_Who_Parked_This_Document,
t.Day_Of_Parking_Of_Accounting_Document,
t.Time_Of_Parking,
t.Parking_Transaction,
t.Branch_Number,
t.Number_Of_Pages_Of_Invoice,
t.Indicator_Entry_Represents_A_Discount_Document,
t.Reference_Key_1_Internal_For_Document_Header,
t.Reference_Key_2_Internal_For_Document_Header,
t.Specifies_Whether_Doc_Is_Reversal_Doc_Or_Reversed_Doc,
t.Invoice_Receipt_Date,
t.Ledger_In_General_Ledger_Accounting,
t.Ledger_Group,
t.Real_Estate_Management_Mandate,
t.Alternative_Reference_Number,
t.Tax_Reporting_Date,
t.Classification_Of_An_Fi_Document,
t.Fi_Document_Originates_From_Split_Posting_Indicator,
t.Cash_Relevant_Document,
t.Follow_On_Document_Indicator,
t.Doc_Contains_Open_Item_That_Was_Transferred_During_Reorg,
t.Defines_Subset_Of_Components_For_The_FiCo_Interface,
t.Exchange_Rate_Type,
t.Market_Data_Exchange_Rate,
t.Market_Data_Exchange_Rate_2,
t.Market_Data_Exchange_Rate_3,
t.Document_Originates_From_Multi_Currency_Accounting,
t.Date_Of_Resubmission,
t.Document_Status_1,
t.Document_Category_Payment_Requests,
t.Reason,
t.Region,
t.Reason_For_Reversal_Is_Ps_Requests,
t.Is_Ps_File_Number,
t.Interest_Formula,
t.Interest_Calc_Date,
t.Posting_Day,
t.Actual_Posting,
t.Date_Of_Last_Change,
t.Last_Changed_At,
t.Type_Of_Payment_Transfer,
t.Payment_Cards_Card_Type,
t.Payment_Cards_Card_Number,
t.Payment_Statistical_Sampling_Block,
t.Lot_Number_For_Documents,
t.User_Name_1,
t.Sampled_Invoice_By_Payment_Certification,
t.Ppa_Exclude_Indicator_BKPF,
t.Budgetary_Ledger_Indicator,
t.Treasury_Offset_Status,
t.Date_Record_Referred_To_Treasury,
t.Reason_For_Late_Payment_BKPF,
t.Number_Of_The_Document_Condition,
t.Type_Of_Payment_Basis_Document,
t.Payment_Basis_Document_Number,
t.Payment_Basis_Document_Date,
t.Iban_International_Bank_Account_Number,
t.Incoming_Document_Number,
t.Incoming_Document_Date,
t.LAST_DTM,
t.Number_Of_Line_Item_Within_Accounting_Document,
t.Identification_Of_The_Line_Item,
t.Clearing_Date,
t.Clearing_Entry_Date,
t.Document_Number_Of_The_Clearing_Document,
t.Posting_Key,
t.Account_Type,
t.Special_GL_Indicator,
t.Special_GL_Transaction_Type,
t.Target_Special_GL_Indicator,
t.Debit_Credit_Indicator,
t.Business_Area,
t.Trading_PartnerS_Business_Area,
t.Tax_On_Sales_Purchases_Code,
t.Withholding_Tax_Code,
t.Amount_In_Local_Currency,
t.Amount_In_Document_Currency,
t.Original_Reduction_Amount_In_Local_Currency,
t.Amount_For_Updating_In_General_Ledger,
t.Update_Currency_For_General_Ledger_Transaction_Figures,
t.Original_Tax_Base_Amount_In_Local_Currency,
t.Original_Tax_Base_Amount_In_Document_Currency,
t.Tax_Amount_In_Local_Currency,
t.Tax_Amount_In_Document_Currency,
t.Tax_Base_Amount_In_Local_Currency,
t.Tax_Base_Amount_In_Document_Currency,
t.Provision_Amount_In_Local_Currency,
t.Additional_Tax_In_Document_Currency,
t.DebitCredit_Addition_For_Cash_Discount,
t.Version_Number_Component,
t.Tax_Type,
t.Group_Indicator_For_Tax_Line_Items,
t.Transaction_Key,
t.Withholding_Tax_Base_Amount,
t.Hedged_Exchange_Rate,
t.Hedged_Amount_In_Foreign_Currency,
t.Valuation_Difference,
t.Valuation_Difference_For_The_Second_Local_Currency,
t.Value_Date,
t.Assignment_Number,
t.Item_Text,
t.Exempted_From_Interest_Calculation,
t.Company_Id_Of_Trading_Partner,
t.Transaction_Type,
t.Group_Account_Number,
t.Transaction_Type_For_General_Ledger,
t.Planning_Level,
t.Planning_Group,
t.Planned_Amount_In_Document_Or_GL_Account_Currency,
t.Planning_Date,
t.Financial_Budget_Item,
t.Controlling_Area,
t.Cost_Center,
t.Old_Project_Number_No_Longer_Used_PsPosnr,
t.Order_Number,
t.Billing_Document,
t.Sales_Document,
t.Sales_Document_Item,
t.Schedule_Line_Number,
t.Main_Asset_Number,
t.Asset_Subnumber,
t.Asset_Transaction_Type,
t.Asset_Value_Date,
t.Personnel_Number,
t.Indicator_Sales_Related_Item,
t.Indicator_Resident_GL_Account,
t.Indicator_Can_Line_Items_Be_Displayed_By_Account,
t.Indicator_Open_Item_Management,
t.Indicator_Address_And_Bank_Data_Set_Individually,
t.Indicator_Statistical_Posting_To_Cost_Center,
t.Indicator_Posting_To_Order_Is_Statistical,
t.Indicator_Posting_To_Project_Is_Statistical,
t.Indicator_Posting_To_Profitability_Analysis_Is_Statistical,
t.Indicator_Billing_Document_Update_Successful,
t.Indicator_Transfer_Posting_From_Down_Payment,
t.Indicator_Down_Payment_In_Net_Procedure,
t.Indicator_Line_Item_Not_Liable_To_Cash_Discount,
t.Indicator_Capital_Goods_Affected,
t.Display_Item,
t.Indicator_Line_Item_Automatically_Created,
t.Indicator_Items_Cannot_Be_Copied,
t.Indicator_Is_Posting_Key_Used_In_A_Payment_Transaction,
t.GL_Account_Number,
t.General_Ledger_Account,
t.Customer_Number,
t.Account_Number_Of_Supplier,
t.Account_Number_Of_The_Branch,
t.Indicator_Account_Is_A_Balance_Sheet_Account,
t.PL_Statement_Account_Type,
t.Assignment_Number_For_Special_GL_Accounts,
t.Baseline_Date_For_Due_Date_Calculation,
t.Terms_Of_Payment_Key,
t.Cash_Discount_Days_1,
t.Cash_Discount_Days_2,
t.Net_Payment_Terms_Period,
t.Cash_Discount_Percentage_1,
t.Cash_Discount_Percentage_2,
t.Amount_Eligible_For_Cash_Discount_In_Document_Currency,
t.Cash_Discount_Amount_In_Local_Currency,
t.Cash_Discount_Amount_In_Document_Currency,
t.Payment_Method,
t.Payment_Block_Key,
t.Fixed_Payment_Terms,
t.Short_Key_For_A_House_Bank,
t.Partner_Bank_Type,
t.Net_Payment_Amount,
t.Tax_Code_For_Distribution_1,
t.Amount_In_Local_Currency_For_Tax_Distribution_1,
t.Amount_In_Foreign_Currency_For_Tax_Breakdown_1,
t.Tax_Code_For_Distribution_2,
t.Amount_In_Local_Currency_For_Tax_Distribution_2,
t.Amount_In_Foreign_Currency_For_Tax_Breakdown_2,
t.Tax_Code_For_Distribution_3,
t.Amount_In_Local_Currency_For_Tax_Distribution_3,
t.Amount_In_Foreign_Currency_For_Tax_Breakdown_3,
t.Document_No_Of_The_Invoice_To_Which_The_Transaction_Belongs,
t.Fiscal_Year_Of_The_Relevant_Invoice_For_Credit_Memo,
t.Line_Item_In_The_Relevant_Invoice,
t.Follow_On_Document_Type,
t.Customs_Tariff_Number,
t.Customs_Date,
t.State_Central_Bank_Indicator,
t.Supplying_Country,
t.Service_Indicator_Foreign_Payment,
t.Invoice_List_Number,
t.Settlement_Period,
t.Insurance_Indicator,
t.Insurance_Date,
t.Number_Of_Bill_Of_Exchange_Usage_Document_Discount_Doc,
t.Fiscal_Year_Of_Bill_Of_Exchange_Usage_Document,
t.Line_Item_Within_The_Bill_Of_Exchange_Usage_Document,
t.Bill_Of_Exchange_Usage_Type,
t.Document_Number_Of_The_Bill_Of_Exchange_Payment_Request,
t.Fiscal_Year_Of_The_Bill_Of_Exchange_Payment_Request_Document,
t.Company_Code_In_Which_Bill_Of_ExchPayment_Request_Is_Posted,
t.Bill_Of_Exchange_Payment_Request_Due_Date,
t.Base_Amount_For_Determining_The_Preference_Amount,
t.Subsidy_Indicator_For_Determining_The_Reduction_Rates,
t.Preference_Percentage_Rate,
t.Dunning_Key,
t.Dunning_Block,
t.Date_Of_Last_Dunning_Notice,
t.Dunning_Level,
t.Dunning_Area,
t.Isr_Subscriber_Number,
t.IsrQr_Reference_Number,
t.Por_Check_Digit,
t.Credit_Control_Amount,
t.Certificate_Number_Of_The_Withholding_Tax_Exemption,
t.Withholding_Tax_Amount_In_Document_Currency,
t.Withholding_Tax_Exempt_Amount_In_Document_Currency,
t.Non_Deductible_Input_Tax_In_Local_Currency,
t.Non_Deductible_Input_Tax_In_Document_Currency,
t.Material_Number,
t.Plant,
t.Quantity,
t.Base_Unit_Of_Measure,
t.Quantity_In_Unit_Of_Entry,
t.Unit_Of_Entry,
t.Quantity_In_Purchase_Order_Price_Unit,
t.Order_Price_Unit_Purchasing,
t.Purchasing_Document_Number,
t.Item_Number_Of_Purchasing_Document,
t.Sequential_Number_Of_Account_Assignment,
t.Delivery_Completed_Indicator,
t.Price_Control_Indicator,
t.Price_Unit,
t.Valuation_Area,
t.Valuation_Type,
t.Posting_String_For_Values,
t.Invoice_Value_Entered_In_Local_Currency,
t.Invoice_Value_In_Foreign_Currency,
t.Amount_Qualifying_For_Bonus_In_Local_Currency,
t.Amount_Posted_In_Alternative_Price_Control,
t.Alternative_Price_Control,
t.New_Price,
t.Indicator_Subsequent_DebitCredit,
t.Blocking_Reason_Price,
t.Blocking_Reason_Quantity,
t.Blocking_Reason_Date,
t.Blocking_Reason_Order_Price_Quantity,
t.Blocking_Reason_Project_Budget,
t.Manual_Blocking_Reason,
t.Vat_Registration_Number,
t.Country_Of_Destination_For_Delivery_Of_Goods,
t.Supplying_Country_For_Delivery_Of_Goods,
t.Reason_Code_For_Payments,
t.Year_Of_Acquisition,
t.Period_Of_Acquisition,
t.Exchange_Rate_GainLoss_Realized,
t.Exchange_Rate_Difference_Realized_For_Second_Local_Currency,
t.Profit_Center,
t.Indicator_GL_Account_Assigned_Manually,
t.Joint_Venture,
t.Recovery_Indicator,
t.Equity_Group,
t.Partner_Account_Number,
t.Contract_Type,
t.Contract_Number,
t.Flow_Type,
t.Securities_Account,
t.Tax_Jurisdiction,
t.Internal_Key_For_Real_Estate_Object,
t.Reference_Date_For_Settlement,
t.Real_Estate_Option_Rate,
t.Commitment_Item,
t.Cost_Object,
t.Network_Number_For_Account_Assignment,
t.Task_List_Number_For_Operations_In_Order,
t.General_Counter_For_Order,
t.Work_Breakdown_Structure_Element_Wbs_Element,
t.Profitability_Segment_Number_Co_Pa,
t.Profitability_Segment_Changes_Co_Pa,
t.Blocking_Reason_Item_Amount,
t.Blocking_Reason_Quality,
t.Payroll_Type,
t.Equity_Type,
t.Indicator_Triangular_Deal_Within_The_Eu,
t.Sequence_Number_Of_Asset_Line_Items_In_Fiscal_Year,
t.Origin_Group_As_Subdivision_Of_Cost_Element,
t.Amount_In_Second_Local_Currency,
t.Amount_In_Third_Local_Currency,
t.Amount_In_Second_Local_Currency_For_Tax_Breakdown_21,
t.Amount_In_Second_Local_Currency_For_Tax_Breakdown_22,
t.Amount_In_Second_Local_Currency_For_Tax_Breakdown_23,
t.Amount_In_Third_Local_Currency_For_Tax_Breakdown_31,
t.Amount_In_Third_Local_Currency_For_Tax_Breakdown_32,
t.Amount_In_Third_Local_Currency_For_Tax_Breakdown_33,
t.Tax_Amount_In_Second_Local_Currency,
t.Tax_Amount_In_Third_Local_Currency,
t.Non_Deductible_Input_Tax_In_Second_Local_Currency,
t.Non_Deductible_Input_Tax_In_Third_Local_Currency,
t.Cash_Discount_Amount_In_Second_Local_Currency,
t.Cash_Discount_Amount_In_Third_Local_Currency,
t.Valuation_Difference_For_The_Third_Local_Currency,
t.Exchange_Rate_Difference_Realized_For_Third_Local_Currency,
t.Method_With_Which_The_Local_Currency_Amount_Was_Determined,
t.Update_Method_For_Fm_Fi_Ca_Integration,
t.Indicator_Clearing_Was_Reversed,
t.Payment_Method_Supplement,
t.Alternative_Account_Number_In_Company_Code,
t.Funds_Center,
t.Fund,
t.Tax_Company_Code,
t.Tax_BaseOriginal_Tax_Base_In_Second_Local_Currency,
t.Tax_BaseOriginal_Tax_Base_In_Third_Local_Currency,
t.Partner_Profit_Center,
t.Business_Partner_Reference_Key_1,
t.Business_Partner_Reference_Key_2,
t.Document_Number_For_Earmarked_Funds,
t.Earmarked_Funds_Document_Item,
t.Tax_Amount_As_Statistical_Information_In_Document_Currency,
t.Functional_Area,
t.Number_Of_Line_Item_In_Original_Document,
t.Indicator_Negative_Posting,
t.Payment_Card_Item,
t.Payment_Cards_Settlement_Run,
t.Credit_Control_Area,
t.PayeePayer,
t.Reference_Key_For_Line_Item,
t.Instruction_1,
t.Instruction_2,
t.Instruction_3,
t.Instruction_4,
t.Activity_Code_For_Gross_Income_Tax,
t.Region_State_Province_County,
t.Distribution_Type_For_Employment_Tax,
t.Indicator_Items_From_Payment_Program_Blocked,
t.Payment_Reference,
t.Credit_Management_Hedged_Amount,
t.Inflation_Index,
t.Last_Adjustment_Date,
t.Account_Assignment_Category_For_Industry_Solution,
t.Acct_Assignment_String_For_Industry_Specific_Acct_Assignmnts,
t.Date_For_Defining_Tax_Rates,
t.Clearing_Item,
t.Currency_For_Automatic_Payment,
t.Amount_In_Payment_Currency,
t.Business_Place,
t.Section_Code,
t.Activity_Type,
t.Accounts_Receivable_Pledging_Indicator,
t.Business_Process,
t.Realized_Exchange_Rate_GainLoss_1LocCurrPart_Payments,
t.Realized_Exchange_Rate_GainLoss_2Loc_CurrPart_Payments,
t.Realized_Exchange_Rate_GainLoss_3LocCurrPart_Payments,
t.Penalty_Charge_Amount_In_First_Local_Currency,
t.Penalty_Charge_Amount_In_Second_Local_Currency,
t.Penalty_Charge_Amount_In_Third_Local_Currency,
t.Penalty_Charge_Amount_In_Document_Currency,
t.Number_Of_Days_For_Penalty_Charge_Calculation,
t.Reason_For_Late_Payment_BSEG,
t.Grant,
t.Tax_Portion_Fi_Ca_Local_Currency,
t.Functional_Area_Long,
t.Item_Is_In_Execution,
t.Type_Of_Additional_Receivable,
t.Internal_Real_Estate_Master_Data_Code,
t.Funded_Program,
t.Fiscal_Year_Of_Clearing_Document,
t.Ppa_Exclude_Indicator_BSEG,
t.Six_Character_Posting_Item_For_Ledger,
t.Segment_For_Segmental_Reporting,
t.Partner_Segment_For_Segmental_Reporting,
t.Partner_Functional_Area,
t.Id_For_Account_Details,
t.Cost_Element,
t.Clearing_Specific_To_Ledger_Groups,
t.Tax_Document_Item_Number,
t.Billing_Period_Of_Performance_Start_Date,
t.Billing_Period_Of_Performance_End_Date,
t.Ppa_Fast_Pay_Indicator,
t.Production_Month_Date_To_Find_Period_And_Year,
t.Ingested_At,
t.Source_ID
 FROM `{uc_catalog_name}`.`{uc_eh_schema}`.FACT_FI_GL_ACCOUNTING_TSAP t """)

assignViewPermission(uc_catalog_name,uc_eh_schema,minerva_acct_tsap_view_name,tbl_owner_grp, security_minerva_readers_aad_group, security_object_aad_group_name, security_functional_readers_aad_group)          
print("Minerva VW_FACT_FI_GL_ACCOUNTING_TSAP view dropped and recreated in the schema")

# COMMAND ----------

# DBTITLE 1,FI_GL_BALANCE_STN View
minerva_balance_stn_view_name = "VW_FACT_FI_GL_BALANCE_STN"
security_function_name = "sf_gen_rls_security"
security_schema = "eh-ds-security"
use_catalog = "USE CATALOG `"+uc_catalog_name+"`"
spark.sql(use_catalog)
spark.sql(f"""DROP VIEW IF EXISTS `{uc_catalog_name}`.`{uc_eh_schema}`.{minerva_balance_stn_view_name}""")
spark.sql(f"""CREATE OR REPLACE VIEW `{uc_catalog_name}`.`{uc_eh_schema}`.{minerva_balance_stn_view_name} 
        AS SELECT t.Reference_Document_Number,
t.Reference_Procedure,
t.Reference_Organisational_Units,
t.Ledger,
t.Document_Type,
t.Fiscal_Year,
t.Doc_Number,
t.Posting_Date_In_The_Document,
t.Record_Type,
t.Version,
t.Company,
t.Company_Code,
t.FI_SL_Document_Type,
t.Accounting_Document_Number,
t.LAST_DTM,
t.Ingested_At,
t.Source_ID
 FROM `{uc_catalog_name}`.`{uc_eh_schema}`.FACT_FI_GL_BALANCE_STN t """)

assignViewPermission(uc_catalog_name,uc_eh_schema,minerva_balance_stn_view_name,tbl_owner_grp, security_minerva_readers_aad_group, security_object_aad_group_name, security_functional_readers_aad_group)          
print("Minerva VW_FACT_FI_GL_BALANCE_STN view dropped and recreated in the schema")

# COMMAND ----------

# DBTITLE 1,FI_GL_BALANCE_TSAP View
minerva_balance_tsap_view_name = "VW_FACT_FI_GL_BALANCE_TSAP"
security_function_name = "sf_gen_rls_security"
security_schema = "eh-ds-security"
use_catalog = "USE CATALOG `"+uc_catalog_name+"`"
spark.sql(use_catalog)
spark.sql(f"""DROP VIEW IF EXISTS `{uc_catalog_name}`.`{uc_eh_schema}`.{minerva_balance_tsap_view_name}""")
spark.sql(f"""CREATE OR REPLACE VIEW `{uc_catalog_name}`.`{uc_eh_schema}`.{minerva_balance_tsap_view_name} 
        AS SELECT t.Reference_Document_Number,
t.Reference_Procedure,
t.Reference_Organisational_Units,
t.Ledger,
t.Document_Type,
t.Fiscal_Year,
t.Doc_Number,
t.Posting_Date_In_The_Document,
t.Record_Type,
t.Version,
t.Company,
t.Company_Code,
t.FI_SL_Document_Type,
t.Accounting_Document_Number,
t.LAST_DTM,
t.Ingested_At,
t.Source_ID
 FROM  `{uc_catalog_name}`.`{uc_eh_schema}`.FACT_FI_GL_BALANCE_TSAP t """)

assignViewPermission(uc_catalog_name,uc_eh_schema,minerva_balance_tsap_view_name,tbl_owner_grp, security_minerva_readers_aad_group, security_object_aad_group_name, security_functional_readers_aad_group)          
print("Minerva VW_FACT_FI_GL_BALANCE_TSAP view dropped and recreated in the schema")
